---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "operator.fullname" . }}-secrets
  labels:
    {{- include "operator.labels" . | nindent 4 }}
type: Opaque
data:
  APIKEY: "{{ .Values.operatorCreds.APIKEY | default "" | b64enc }}"
  HOSTNAME: "{{ .Values.operatorCreds.HOSTNAME | default "" | b64enc }}"
  USERNAME: "{{ .Values.operatorCreds.USERNAME | default "" | b64enc }}"
