apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: https
      protocol: TCP
      name: metrics
    {{- if .Values.kubeRBACProxy.enabled }}
    - name: https
      port: {{ .Values.kubeRBACProxy.ports.proxyPort }}
      protocol: TCP
      targetPort: https
    {{- end }}
    {{- range .Values.extraPorts }}
      - port: {{ .port }}
        targetPort: {{ .port }}
        protocol: TCP
        name: {{ .name }}
    {{- end }}
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  name: {{ template "operator.fullname" . }}-webhook
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}