apiVersion: v1
kind: Service
metadata:
  name: {{ include "operator.fullname" . }}
  labels:
    {{- include "operator.labels" . | nindent 4 }}
  annotations:
    {{ toYaml .Values.service.annotations | indent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.port }}
      targetPort: https
      protocol: TCP
      name: https
    {{- range .Values.extraPorts }}
      - port: {{ .port }}
        targetPort: {{ .port }}
        protocol: TCP
        name: {{ .name }}
    {{- end }}
  selector:
    {{- include "operator.selectorLabels" . | nindent 4 }}
